---

# This is a collection of monitors to check various states at regular scheduled intervals.
# Monitors performed:
#  Check for dockers last 15 minutes

# Settings to edit:
# All "dockercheck_" entries

- name: Install Monitors
  hosts: all
  vars:
    dockercheck_minute: '*/5' # Checks every 15 minutes
    dockercheck_hour: '*'
    dockercheck_day: '*'
    dockercheck_month: '*'
    dockercheck_weekday: '*'
  gather_facts: no

  tasks:
    - name: Clone OT-NodeWatch git repository
      git:
        repo: 'https://github.com/calr0x/OT-NodeWatch.git'
        dest: /root/OT-NodeWatch
        force: yes

    - name: Clone OT-Settings git repository
      git:
        repo: 'https://github.com/calr0x/OT-Settings.git'
        dest: /root/OT-Settings
        force: yes

    - name: Copy config file
      copy:
        src: /root/OT-Settings/config.sh
        dest: /root/OT-Settings

    - name: Delete existing monitor (docker check) schedule from cron
      cron:
        name: Monitor Docker Check
        state: absent

    - name: Add monitor (docker check) schedule to cron (every 15 minutes)
      cron:
        name: Monitor Docker Check
        minute: "{{ dockercheck_minute }}"
        hour: "{{ dockercheck_hour }}"
        day: "{{ dockercheck_day }}"
        month: "{{ dockercheck_month }}"
        weekday: "{{ dockercheck_weekday }}"
        job: "/root/OT-NodeWatch/docker_check/docker_check.sh"
